import { MovieCastModel } from './movie-cast.model';
import { MovieCategoryModel } from './movie-category.model';
import { MovieCreditsModel } from './movie-credits.model';
import { MovieCrewModel } from './movie-crew.model';
import { MovieDetailsModel } from './movie-details.model';
import { MovieGenreModel } from './movie-genre.model';
import { MoviePersonModel } from './movie-person.model';
import { MovieVideosModel } from './movie-videos.model';
import { MovieModel } from './movie.model';
import { TvCastModel } from './tv-cast.model';
import { TvCreditsModel } from './tv-credits.model';
import { TvCrewModel } from './tv-crew.model';

export * from './movie-cast.model';
export * from './movie-category.model';
export * from './movie-credits.model';
export * from './movie-crew.model';
export * from './movie-details.model';
export * from './movie-genre.model';
export * from './movie-person.model';
export * from './movie-videos.model';
export * from './movie.model';
export * from './tv-cast.model';
export * from './tv-credits.model';
export * from './tv-crew.model';
